version: '3'
services:
  web:
    build: .
    #image: bitcoin_server_msa:latest
    environment:
      MONGODB_HOST: mongodb
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
    # networks:
    #   - likelion_default
  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=AI
      - MONGO_INITDB_ROOT_USERNAME=user_name
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - .:/mongodb
    ports:
      - 27017:27017
#     networks:
#       - likelion_default
# networks:
#   likelion_default:
#     external: true