dependencies:
  - python=3.9
  - conda=23.3.1 # Use the version that works for your setup
  - flask==2.0.2
  - pip:
    - py_eureka_client
    - apscheduler
    - openai==0.27.7
    - pymysql
    - scikit-learn
    - numpy
    - werkzeug==2.0.2
    - keras
    - pandas
    - pylint
    - pycodestyle
    - autopep8
    - mypy
    - tensorflow==2.11
    # - tensorflow-gpu==2.11  # GPU 지원을 위한 TensorFlow
    # - tensorflow-estimator==2.12.0
    # - tensorflow-intel==2.12.0

# name: flask-app
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - openai
#   - python=3.6
#   - flask-cors
#   - flask-restful
#   - ipython
#   - gunicorn
#   - jupyterhub
#   - py_eureka_client
#   - pymysql
#   - apscheduler
#   - openai
#   - pymysql
#   - scikit-learn
#   - numpy
#   - werkzeug==2.0.2
#   - keras
#   - pandas
#   - pylint
#   - pycodestyle
#   - autopep8
#   - tensorflow
    # - tensorflow-estimator==2.12.0
    # - tensorflow-intel==2.12.0